name: ssiamb
channels:
  - bioconda
  - conda-forge
dependencies:
  - bbmap=39.33=h75f4405_0
  - bcftools=1.22=h0a67c2f_1
  - bwa-mem2=2.3=h2ec61ea_0
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - gsl=2.7=h93259b0_0
  - htslib=1.22.1=h9f635df_0
  - k8=1.2=h2ec61ea_6
  - krb5=1.21.3=h37d8d59_0
  - libblas=3.9.0=35_he492b99_openblas
  - libcblas=3.9.0=35_h9b27e0a_openblas
  - libcurl=8.14.1=h5dec5d8_0
  - libcxx=21.1.1=h3d58e20_0
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - libgfortran=15.1.0=h5f6db21_1
  - libgfortran5=15.1.0=hfa3c126_1
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h83c2472_2
  - libsqlite=3.50.4=h39a8b3b_0
  - libssh2=1.11.1=hed3591d_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.0=hf4e0ed4_0
  - minimap2=2.30=h7f84b70_0
  - mosdepth=0.3.11=h4556f9c_1
  - ncurses=6.5=h0622a9a_3
  - openjdk=24.0.2=h2d74430_0
  - openssl=3.5.2=h6e31bce_0
  - perl=5.32.1=7_h10d778d_perl5
  - pip=25.2=pyh8b19718_0
  - python=3.12.11=h9ccd52b_0_cpython
  - readline=8.2=h7cca4af_2
  - samtools=1.22.1=ha21ef43_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=hf689a15_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=h8210216_2
  - pip:
      # Core runtime dependencies
      - biopython==1.85
      - numpy==2.3.3
      - pandas==2.3.2
      - pysam==0.23.3
      - pyyaml==6.0.2
      - typer==0.17.4
      - rich==14.1.0
      - click==8.2.1
      - shellingham==1.5.4
      
      # Development and build tools
      - black==25.1.0
      - ruff==0.13.1
      - mypy==1.18.1
      - mypy-extensions==1.1.0
      - types-PyYAML
      - pandas-stubs
      
      # Testing tools
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - coverage==7.10.6
      - iniconfig==2.1.0
      - pluggy==1.6.0
      
      # Packaging and build tools
      - build==1.3.0
      - hatchling==1.27.0
      - packaging==25.0
      - pyproject-hooks==1.2.0
      - trove-classifiers==2025.9.11.17
      
      # Additional utilities and dependencies
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - pathspec==0.12.1
      - platformdirs==4.4.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      
      # Legacy tools (can be removed if not needed)
      - flake8==7.3.0
      - mccabe==0.7.0
prefix: /Users/B246654/vscode_storage/ssi-dk/ssiamb/env
